# These are normally to be appended to the bashrc.

# Make terminal useable
set -o vi

# Get date in YYYY-MM-DD form.
D() {
    date +"%Y-%m-%d"
}

# Shorter alias for opening things using the default GUI application.
alias s='xdg-open'

# Find a file by name or regex and vim into it.
fvim() {
    find . -name "$1" -exec vim {} \;
}

# Enable forward-i-search by disabling flow control
stty -ixon

alias fp='readlink -f '
export PATH=$PATH:/home/hq6/Research/A/arachne-sosp2017/scripts
export PATH=$PATH:/home/hq6/Research/A/CacheTools
export PATH=$PATH:/home/hq6/Research/A/CacheTools/PerfUtils/scripts

# Sometimes we want to sudo while preserving our own PATH.
alias psudo='sudo env "PATH=$PATH" '

# Mostly for laptops, this is a nice convenience.
alias battery=acpi

# Aliases for when one wants to try typing without echo.
alias a='stty echo && clear'
alias d='stty -echo && clear'

alias ta='tmux at'
